markdown: kramdown


kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: true

collections:
  contents:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: contents
    values:
      layout: default